fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    inifile: "https://github.com/puppetlabs/puppetlabs-inifile.git"
    archive: "https://github.com/puppet-community/puppet-archive.git"
    dirtree: "https://github.com/puppetlabs/pltraining-dirtree.git"
    java_ks: "https://github.com/puppetlabs/puppetlabs-java_ks.git"
    apt: "https://github.com/puppetlabs/puppetlabs-apt.git"
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
      puppet_version: ">= 6.0.0"
    augeas_core:
      repo: https://github.com/puppetlabs/puppetlabs-augeas_core.git
      puppet_version: ">= 6.0.0"
